let humanMale = [
  'Abeodan',
  'Ace',
  'Aewel',
  'Aelle',
  'Aheawan',
  'Alchfrith',
  'Aldhelm',
  'Alfred',
  'Algar',
  'Alger',
  'Almund',
  'Alwin',
  'Andettan',
  'Andsaca',
  'Andswaru',
  'Andwyrdan',
  'Ane',
  'Archerd',
  'Archibald',
  'Arlice',
  'Astyrian',
  'Avery',
  'Baldlice',
  'Bana',
  'Banan',
  'Bar',
  'Bawdewyn',
  'Beadurinc',
  'Benoic',
  'Benwick',
  'Besyrwan',
  'Betlic',
  'Bronson',
  'Caedwalla',
  'Caflice',
  'Camden',
  'Chapman',
  'Cynewulf',
  'Cynn',
  'Dalston',
  'Deogol',
  'Derian',
  'Drefan',
  'Dreogan',
  'Eadig',
  'Eadlyn',
  'Eamon',
  'Ecgfrith',
  'Edmund',
  'Edmund',
  'Eldrdid',
  'Eorl',
  'Farmon',
  'Garrett',
  'Geoff',
  'Gildas',
  'Gimm',
  'Graeme',
  'Grendel',
  'Grimbold',
  'Grimme',
  'Halig',
  'Ham',
  'Landry',
  'Lange',
  'Lars',
  'Leax',
  'Leng',
  'Leof',
  'Lin',
  'List',
  'Lufian',
  'Manton',
  'Norville',
  'Odi',
  'Odin',
  'Oswine',
  'Peada',
  'Perry',
  'Pierce',
  'Prasutagus',
  'Ramma',
  'Rand',
  'Rinc',
  'Ro',
  'Rypan',
  'Scrydan',
  'Seward',
  'Sihtric',
  'Stearc',
  'Stedman',
  'Swift',
  'Tamar',
  'Toaln',
  'Trace',
  'Waelwulf',
  'Winter',
  'Wissian',
  'Worthington',
];
let humanFemale = [
  'Acca',
  'Aedra',
  'Aefentid',
  'Aefre',
  'Aethelflaed',
  'Aethelthryth',
  'Alodia',
  'Alodie',
  'Andsware',
  'Anlienes',
  'Annis',
  'Ar',
  'Ardith',
  'Arianrod',
  'Ashley',
  'Audrey',
  'Bearrocscir',
  'Bernia',
  'Bisgu',
  'Bletsung',
  'Bliss',
  'Blythe',
  'Bodiciea',
  'Brigantia',
  'Brimlad',
  'Bysen',
  'Cartimandua',
  'Cearo',
  'Chelsea',
  'Claennis',
  'Clover',
  'Cwen',
  'Cyst',
  'Daedbot',
  'Daisy',
  'Darel',
  'Darelene',
  'Darelle',
  'Darline',
  'Daryl',
  'Dawn',
  'Devona',
  'Dohtor',
  'Donna',
  'Eacnung',
  'Eadgyth',
  'Easter',
  'Eda',
  'Edith',
  'Edlyn',
  'Edmunda',
  'Edrys',
  'Eldrida',
  'Elene',
  'Elga',
  'Ellenweore',
  'Ellette',
  'Elswyth',
  'Elva',
  'Elvina',
  'Engel',
  'Eostre',
  'Erlina',
  'Esma',
  'Estra',
  'Etheswitha',
  'Freya',
  'Garmangabis',
  'Hamia',
  'Harimilla',
  'Hilda',
  'Ifield',
  'Juliana',
  'Kendra',
  'Linette',
  'Lora',
  'Loretta',
  'Lyn',
  'Mae',
  'Maida',
  'Megan',
  'Merica',
  'Moira',
  'Nelda',
  'Nethus',
  'Odelia',
  'Ora',
  'Orva',
  'Osberga',
  'Rheda',
  'Sibley',
  'Silver',
  'Sulis',
  'Sunniva',
  'Tate',
  'Udele',
  'Viradecthis',
  'Wilda',
  'Willa',
];
let dwarfMale = 'Babbar,Borar,Dalor,Dragir,Gindor,Givli,Mavon,Ravan,Thodor,Thorli';
let dwarfFemale = 'Thorva,Thorgana,Tholga,Melviel,Glorna,Giva,Dragrina,Dagna,Belrin,Baergi';
let elfMale = 'Analith,Celaith,Elromir,Fondel,Galoldur,Horfir,Legoriand,Tinilith,Thrund,Unaramir';
let elfFemale =
  'Cadrielith.Deleviel,Eariothiel,Elronia,Galaniel,Legarawen,Milmalith,Sithrade,Tinoniel,Throrfiviel';
let halflingMale = 'Adelard,Andwise,Calkin,Eldon,Falco,Griffo,Halfred,Olo,Rosco,Scredoc';
let halflingFemale =
  'Amaryllia,Carissa,Donamira,Lavinia,Marigold,Myrtle,Pearl,Ruby,Seraphina,Violet';
let equipment = [
  'Rolling Pin, Cask of Ale',
  'Staff, 2 Clay Jars of Honey',
  'Sickle, Mortar & Pestle',
  'Badking Paddle, Sack of Flour',
  'Knife, Lute',
  'Knife, Sturdy Basket',
  'Begging Bowl, 2 Coins',
  'Hammer, Burlap Sack, 2 Iron Ingots',
  'Handaxe, 7 Planks of Wood',
  'Shortbow +1 Damage, Arrows, Sets of Staves & Sinews',
  'Trowel, Hod, 3 Bricks',
  'Prybar, Burlap Sack',
  'Cleaver, Side of Salted Beef',
  'Handaxe, Hand Saw',
  'Handaxe, Pushcart',
  'Club, Shoulder Bag, 8 Coins',
  'Staff, 3 Candles',
  'Staff, Rucksack, Smoked Fish',
  'Staff, Burlap Sack, Wheel of Cheese',
  'Tack Hammer,3 Pairs of Boots',
  'Shortsword +1 Damage, Set of Iron Cuffs',
  'Knife, Leather Satchel,Important Letter',
  'Knife, Plumed Hat',
  'Pitchfork, Bushel of Turnips',
  'Pitchfork, Bushel of Potatoes',
  'Pitchfork, Bushel of Onions',
  'Pitchfork, Bushel of Oats',
  'Shovel',
  'Shovel,Pushcart Full of Dung',
  'Pick,Adventuring Gear',
  'Hammer,Burlap Sack, 3 Iron Ingots',
  'Hammer,Chisel',
  'Knife,Burlap Sack,3 Mole Traps',
  'Shortbow +1 Damage,Arrows',
  'Knife, Elven Lyre',
  'Staff, Hooded Cloak +1 Armor',
  'Knife,Bolt of Silk',
  "Executioner's Axe +1 Damage, Black Hood",
  'Knife, Leather Gauntlet +1 Armor',
  'Shortbow +1 Damage,Arrows',
  'Sap, Burlap Sack',
  'Sickle,Burlap Sack,Mushrooms',
  'Shortbow +1 Damage,Arrows',
  'Crook,2 Goats',
  'Crook,3 Goats',
  'Crook,4 Goats',
  'Knife,Fishing Net',
  'Knife,Fishing Net',
  'Knife,Fishing Net',
  'Shovel,Cask of Beer',
  'Cleaver,Meat Pies',
  'Pitchfork, Bushel of Pipeweed',
  'Spade,Wheelbarrow',
  'Staff,Shoulder Bag,Bandages',
  'Staff,Belt Pouch',
  'Shortsword +1 Damage,Trumpet',
  'Staff,Pouch,Poultices & Herbs',
  'Shortbow +1 Damage,Arrows',
  'Shortbow +1 Damage,Arrows',
  'Shortbow +1 Damage,Arrows',
  'Club, Provisions',
  'Hammer,Lantern,Flask of Oil,Flint & Steel',
  'Canvas Sack,Cake of Soap',
  'Club,Sack of Flour',
  'Pick +1 Damage,Lantern,Flask of Oil,Flint & Steel',
  'Staff, Holy Symbol',
  'Knife,Fishing Net,50 Feet of Rope',
  'Longsword +1 Damage,Signet Ring',
  'Whip,Ox',
  'Knife,Rucksack,Healing Potion',
  'Staff,Holy Symbol',
  'Club,Burlap Sack',
  'Knife,Flask of Perfume',
  'Club,Burlack Sack,4 Dead Rats',
  'Club, 100 Feet of Rope',
  'Knife, Cloak',
  "Executioner's Axe +1 Damage, Black Hood",
  'Knife, Leather Gauntlet +1 Armor',
  'Shortbow +1 Damage,Arrows',
  'Sap, Burlap Sack',
  'Sickle,Burlap Sack,Mushrooms',
  'Shortbow +1 Damage,Arrows',
  'Crook,2 Goats',
  'Crook,3 Goats',
  'Crook,4 Goats',
  'Knife,Fishing Net',
  'Knife,Fishing Net',
  'Knife,Fishing Net',
  'Shovel,Cask of Beer',
  'Cleaver,Meat Pies',
  'Pitchfork, Bushel of Pipeweed',
  'Spade,Wheelbarrow',
  'Staff,Shoulder Bag,Bandages',
  'Staff,Belt Pouch',
  'Shortsword +1 Damage,Trumpet',
  'Staff,Pouch,Poultices & Herbs',
  'Shortbow +1 Damage,Arrows',
  'Trowel, Hod, 3 Bricks',
  'Prybar, Burlap Sack',
  'Cleaver, Side of Salted Beef',
];
let personalityTraits = 'Absentminded,Aggressive,Aloof,Ambitious,Arrogant,Callous,Calm,Cantankerous,Cautious,Cheerful,Coarse,Competitive,Conceited,Confident,Conscientious,Courageous,Courteous,Covetous,Cowardly,Crazy,Crude,Curious,Cynical,Daring,Deceitful,Decisive,Dignified,Disciplined,Drunkard,Earnest,Earthy,Efficient,Egocentric,Enthusiastic,Fatalistic,Fiery,Foolish,Forgiving,Forthright,Friendly,Frugal,Generous,Gentle,Good-Natured,Gracious,Greedy,Gullible,Helpful,Honorable,Humble,Hardheaded,Hardened,Impulsive,Kind,Lazy,Libidinous,Loyal,Melancholic,Methodical,Modest,Moralistic,Morbid,Mystical,Naive,Neat,Nihilistic,Obedient,Obsessive,Opportunistic,Optimistic,Outspoken,Parnaoid,Peaceful,Pedantic,Plodding,Power-Hungry,Protective,Proud,Quiet,Realistic,Religious,Romantic,Romantic,Sadistic,Sanctimonious,Sarcastic,Secretive,Selfless,Serious,Shrewd,Solitary,Steadfast,Stoic,Stone-Cold,Stubborn,Superstitious,Suspicious,Thorough,Timid,Treacherous,Trusting';
let malePhysicalTraits =
  'Bald,Balding,Barrel-Chested,Big Feet,Big Hands,Bloodshot Eyes,Blue-Eyed,Bony,Booming Voice,Braided Hair,Broad Brow, Broad Chest, Broad Hips,Broad Shoulders,Buck Teeth,Bushy Eyebrows,Cleft Chin,Crooked Teeth,Curly Hair,Dark Eyes,Dark Skin,Dimples,Dirty,Fair-Haired,Fat,Freckled,Full Lips,Furrowed Brow,Glowering,Gnarled Fingers,Greasy-Looking,Hairless,Hawk-Nosed,High Cheekbones,Hirsute,Hunchback,Husky Voice,Lambchop Sideburns,Lanky,Large Ears,Large Eyes,Large Nose,Lazy Eye,Limp,Long Arms,Long Beard,Long Fingers,Long Legs,Long Mustache,Long Torso,Matted Hair,Missing Teeth,Nasal Voice,Nearsighted,Nose Ring,One Ear,One Eye,One Hand,Pale Skin,Peg Leg,Persistent Cough,Petite,Piercings,Plump,Pop-Eyed,Pot-Bellied,Quiet-Voice,Rosy Cheeks,Ruddy,Scars,Scowly,Sharp Chin,Sharp Fingernails,Short,Short Hair,Skinny,Small Ears,Small Eyes,Small Feet,Small Hands,Small Nose,Smiley,Spade-Like Hands,Square Jaw,Stocky,Stubby Fingers,Swan-Like Neck,Tall,Tattoos,Thick Neck,Unibrow,Wavy Hair,Weathered,Well-Built,Well-Groomed,Wheezy,Whiny,Wild Hair';
let femalePhysicalTraits =
  'Barrel-Chested,Big Feet,Big Hands,Bloodshot Eyes,Blue-Eyed,Bony,Booming Voice,Braided Hair,Broad Brow, Broad Chest, Broad Hips,Broad Shoulders,Buck Teeth,Bushy Eyebrows,Cleft Chin,Crooked Teeth,Curly Hair,Dark Eyes,Dark Skin,Dimples,Dirty,Fair-Haired,Fat,Freckled,Full Lips,Furrowed Brow,Glowering,Gnarled Fingers,Greasy-Looking,Hawk-Nosed,High Cheekbones,Hirsute,Hunchback,Husky Voice,Lanky,Large Ears,Large Eyes,Large Breasts,Large Nose,Lazy Eye,Limp,Long Arms,Long Fingers,Long Legs,Long Torso,Matted Hair,Missing Teeth,Nasal Voice,Nearsighted,Nose Ring,One Ear,One Eye,One Hand,Pale Skin,Peg Leg,Persistent Cough,Petite,Piercings,Plump,Pop-Eyed,Pot-Bellied,Quiet-Voice,Rosy Cheeks,Ruddy,Scars,Scowly,Sharp Chin,Sharp Fingernails,Short,Short Hair,Skinny,Small Ears,Small Eyes,Small Feet,Small Hands,Small Nose,Smiley,Spade-Like Hands,Square Jaw,Stocky,Stubby Fingers,Swan-Like Neck,Tall,Tattoos,Thick Neck,Unibrow,Wavy Hair,Weathered,Well-Built,Well-Groomed,Wheezy,Wild Hair';

module.exports = {
  humanMale,humanFemale,dwarfMale,dwarfFemale,elfMale,elfFemale,halflingMale,halflingFemale,personalityTraits,malePhysicalTraits,femalePhysicalTraits,equipment,
};
